version: 2

workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: master
  build-other-branches:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

jobs:
  test:
    docker:
      - image: node:12.16.1-alpine3.11
    steps:
      - checkout
      - run: |
          apk update && apk upgrade
          apk add --no-cache git openssh make gcc g++ python
      - run:
          name: Install dev dependencies
          command: npm install
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Bootstrap lerna
          command: npm run lerna-reset
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Setup elixir-omg environment
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:omisego/elixir-omg.git ~/elixir-omg
            cd ~/elixir-omg
            docker-compose up
