version: 2

workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: master
  build-other-branches:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

jobs:
  test:
    docker:
      - image: node:12.16.1-alpine3.11
    steps:
      - checkout
      - run: |
          apk update && apk upgrade
          apk add --no-cache git openssh make gcc g++ python
      - run: npm install
      - run: npm run lint
      - run: npm run test
